services:
  mongo_db:
    container_name: DB_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  nodeJS:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT : 3000
      MONGODB_URI : mongo_db://127.0.0.1:27017/chat?directConnection=true&serverSelectionTimeoutMS=2000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}